services:
  nodeserver:
    build:
      context: ./app
    networks:
      - main
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - nodeserver
    networks:
      - main
networks:
  main:
